### PR TITLE
Refactor obfuscated feature modification

### PR DESCRIPTION
**Pull request by marcustyphoon**
No functional changes here, and feel free not to merge this or to just take parts of it. Just some code cleanup suggestions! This:

- Extracts the "obf" modification into a function (I tried to steal this code to test a feature flag, only changed it in one of the locations, and got confused :D)
- Demonstrates javascript object shallow copying using `{ ...spread }` syntax (technically the code was mutating the input to the getter before, although this evidently causes no problems). Good practice, though!
- Demonstrates that you don't have to use a window global to store stuff for later!

### CODE REVIEW

**Comment by marcustyphoon** [comment]
Assuming that the `liveStreamingWeb` property set doesn't have to be conditional, one can also use object spread syntax to overwrite properties of an object in a fairly elegant way, like so:

```js
const modifyOfuscatedFeatures = (obfuscatedFeatures) => {
    const obf = {
        ...JSON.parse(atob(obfuscatedFeatures)), // convert from base64, parse from string
        
        redpopDesktopVerticalNav: false, // disable vertical nav layout
        liveStreamingWeb: false, // no tumblr live
        activityRedesignM3: false, // ugly activity update
        liveStreaming: false, // more live shenanigans
        liveCustomMarqueeData: false,
        liveStreamingWebPayments: false,
        adFreeCtaBanner: false, // no annoying popup when using an adblocker
        domainsSettings: false, // turn off tumblr domains
        messagingRedesign: false, // disable messaging update
        experimentalBlockEditorIsOnlyEditor: false, // allow old post editor
        configurableTabbedDash: true, // new dashboard tab config
        crowdsignalPollsNpf: true, // poll functionality
        crowdsignalPollsCreate: true,
        allowAddingPollsToReblogs: true,
    };
    console.log(obf);
    return btoa(JSON.stringify(obf)); // compress back to string, convert to base64
};
```
---
(It's kind of a pain to do this conditionally; you can use multiple spreads one after the other or it like this:
```js
const result = {
  ...source,
  ...(someCondition
    ? {
        a: 'b',
        c: 'd',
      }
    : {}),
  e: 'f',
  g: 'h',
};

```
but as you can see that's pretty awkward and I assume many people would just mutate the properties instead in a lot of cases, like you're currently doing.)

**Comment by marcustyphoon** [comment]
Aside: `window.___INITIAL_STATE = undefined;` is a typo/unnecessary, right?

**Comment by enchanted-sword** [comment]
> Assuming that the liveStreamingWeb property set doesn't have to be conditional
At one point, it seemed to me like it did, because the number of properties related to Tumblr Live seemingly varies depending what A/B tests an account is part of, and when I was initially testing it, setting that specific property to false on accounts without vertical nav was messing up the order of the SVG icons attached to the navbar, strangely enough. However, I just tested it again now and it seems to work fine to just set it to false regardless.

> Aside: window.___INITIAL_STATE = undefined; is a typo/unnecessary, right?
Yes, I removed it from my testing code but haven't committed the change yet because I was working on another feature. I'll still merge this first because it basically makes some of the same changes I added but neater, and the rest of the things I added are elsewhere in the code

**Review by enchanted-sword — APPROVED** [review]

**Comment by marcustyphoon** [comment]
Thought about this a bit more and also came up with a logic tree that works the same way whether or not `window.___INITIAL_STATE___` has been set already or not: doing the modification in the getter. Of course, this has the potential for a performance impact if the modification code is expensive (it isn't) and if this property gets accessed a ton of times (it doesn't).

```js
let state = window.___INITIAL_STATE___;
Object.defineProperty(window, "___INITIAL_STATE___", { // thanks twilight-sparkle-irl!
    set(x) {
        state = x;
    },
    get() {
        try {
            return {
                ...state,
                obfuscatedFeatures: modifyObfuscatedFeatures(state.obfuscatedFeatures, featureSet)
            };
        } catch (e) {
            console.error("Failed to modify features", e);
        }
        return state;
    },
    enumerable: true,
    configurable: true,
});
```

**Pull request merged**
